catalog/urls.py
from django.urls import path
from . import views
from .views import BBLoginView
from .views import profile
from .views import BBLogoutView
from .views import RegisterDoneView
from .views import RegisterUserView
from .views import create_application
from .views import delete_application



app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/login', BBLoginView.as_view(), name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('create/', create_application, name='create_application'),
    path('delete/<int:application_id>/', delete_application, name='delete_application'),
    path('admin_profile/', views.admin_profile, name='admin_profile'),
    path('create_application/', views.create_application, name='create_application'),
    path('edit_application/<int:application_id>/', views.edit_application, name='edit_application'),
]

design/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class AdvUser(AbstractUser):
   first_name = models.CharField(max_length=100, blank=True, verbose_name='Имя')
   patronymic = models.CharField(max_length=100, blank=True, verbose_name='Отчество')
   last_name = models.CharField(max_length=100, blank=True, verbose_name='Фамилия')

   TARIFF_CHOICES = [
       ('company', 'Для юр.лиц'),
       ('individual', 'Для физ.лиц'),
   ]
   tariff = models.CharField(max_length=20, choices=TARIFF_CHOICES, default='individual', verbose_name='Тариф')

   class Meta(AbstractUser.Meta):
       pass


class Categories(models.Model):
    name = models.CharField(max_length=200, help_text="Введите название категории")

    def __str__(self):
        return self.name


class Application(models.Model):
    date = models.DateField(null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(max_length=1000, help_text="Описание")
    categories = models.ManyToManyField(Categories, help_text="Выберите категорию")
    photo = models.FileField(upload_to='photos/')

    LOAN_STATUS = (
        ('n', 'Новая'),
        ('o', 'Принята в работу'),
        ('d', 'Выполнена'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='n', help_text='Статус заявки')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена', default=10000, blank=True)
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий администратора')
    document = models.FileField(upload_to='documents/', null=True, blank=True, verbose_name='Договор')

catalog/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import AdvUser
from .models import Application
from .models import Categories
from django.core.validators import RegexValidator


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты', validators=[
            RegexValidator(
                regex=r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$',
                message=' Необходим валидный формат email-адреса'
            )
        ])
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label='Пароль (повторно)',
        widget=forms.PasswordInput,help_text='Повторите тот же самый пароль еще раз'
    )
    first_name = forms.CharField(label='Имя', max_length=100, validators=[
            RegexValidator(
                regex=r'^[а-яА-ЯёЁ\s-]+$',
                message='Имя должно состоять только из кириллических букв, пробелов и дефисов.'
            )
        ])
    patronymic = forms.CharField(label='Отчество', max_length=100, validators=[
            RegexValidator(
                regex=r'^[а-яА-ЯёЁ-]+$',
                message='Отчество должно состоять только из кириллических букв и дефисов.'
            )
        ])
    last_name = forms.CharField(label='Фамилия', max_length=100, validators=[
            RegexValidator(
                regex=r'^[а-яА-ЯёЁ-]+$',
                message='Фамилия должно состоять только из кириллических букв и дефисов.'
            )
        ])
    username = forms.CharField(label='Логин', max_length=30, validators=[
            RegexValidator(
                regex=r'^[a-zA-Z-]+$',
                message='Логин должен состоять только из латинских букв и дефисов.'
            )
        ])
    consent = forms.BooleanField(label='Согласие на обработку персональных данных')

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()  #встроенная функция, которая позволяет вызывать методы родительского класса
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            self.add_error('password2', ValidationError(
                'Введенные пароли не совпадают.'
            ))

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'first_name', 'patronymic', 'last_name', 'email', 'password1',
                  'password2', 'tariff', 'consent')


class ApplicationForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(
        queryset=Categories.objects.all(),
    )

    class Meta:
        model = Application
        fields = ('date', 'name', 'description', 'categories', 'photo', 'price')

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo.size > 2 * 1024 * 1024:
            raise forms.ValidationError("Размер фото не должен превышать 2 Мб.")
        return photo

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        application = super().save(commit=False)
        application.user = self.user

        if self.user.tariff == 'company':
            multiplier = 1.20
        elif self.user.tariff == 'individual':
            multiplier = 1.06
        else:
            multiplier = 1.00

        base_price = 10000
        application.price = base_price * multiplier

        if commit:
            application.save()
            self.save_m2m()
        return application


def valid_document(value):
    allowed_formats = ['doc', 'docx', 'odt']
    ext = value.name.split('.')[-1].lower()
    if ext not in allowed_formats:
        raise ValidationError('Недопустимый формат файла. Разрешены только файлы формата doc, docx или odt.')


class ApplicationAdminForm(forms.ModelForm):
    document = forms.FileField(validators=[valid_document], required=False)

    class Meta:
        model = Application
        fields = ('status', 'categories', 'photo', 'comment', 'document')

    def clean(self):
        cleaned_data = super().clean()
        status = cleaned_data.get('status')
        document = cleaned_data.get('document')
        user = self.instance.user

        if status == 'd' and not document:
            self.add_error('document', 'Для измененияч статуса прикрепите докумет!')

        if document and user.tariff != 'company':
            self.add_error('document', 'Только для юр.лиц!')

        return cleaned_data

catalog/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import AdvUser
from django.views.generic import CreateView
from .forms import RegisterUserForm
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.core.mail import send_mail
from django.contrib.auth import login
from .forms import ApplicationForm
from .forms import ApplicationAdminForm
from .models import Application


def index(request):
    num_application_in_work = Application.objects.filter(status__exact='o').count()
    applications = Application.objects.filter(status__exact='d').order_by('-date')[:4]
    return render(
        request,
        'index.html',
        context={'num_application_in_work': num_application_in_work, 'applications': applications})


class BBLoginView(LoginView):
    template_name = 'registration/login.html'


@login_required
def profile(request):
    applications = Application.objects.filter(user=request.user)
    return render(request, 'registration/profile.html', {'applications': applications})


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'registration/logout.html'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'registration/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('catalog:register_done')

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     user = self.object
    #
    #     subject = 'Регистрация на сайте'
    #     message = f'Спасибо за регистрацию! Вы выбрали тариф: {dict(form.TARIFF_CHOICES)[tariff]}'
    #     from_email = 'malenkoer@mail.ru'
    #     recipient_list = [user.email]
    #     send_mail(subject, message, from_email, recipient_list)
    #
    #     try:
    #         send_mail(subject, message, from_email, recipient_list)
    #     except Exception as e:
    #         print(f'Email sending failed: {e}')
    #
    #     login(self.request, user)
    #     return response


class RegisterDoneView(TemplateView):
    template_name = 'registration/register_done.html'


@login_required
def create_application(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            application = form.save()
            return redirect('catalog:profile')
    else:
        form = ApplicationForm(user=request.user)
    return render(request, 'application/create_application.html', {'form': form})


@login_required
def delete_application(request, application_id):
    application = get_object_or_404(Application, id=application_id, user=request.user)

    if application.user != request.user:
        messages.error(request, "У вас нет прав на удаление этой заявки.")
        return redirect('catalog:profile')

    if application.status != 'n':
        messages.error(request, "Заявку нельзя удалить, так как её статус изменён.")
        return redirect('catalog:profile')

    if request.method == 'POST':
        application.delete()
        return redirect('catalog:profile')

    return render(request, 'application/delete_application.html', {'application': application})


@login_required
@user_passes_test(lambda u: u.is_staff)
def edit_application(request, application_id):
    application = get_object_or_404(Application, id=application_id)
    user = application.user
    if request.method == 'POST':
        form = ApplicationAdminForm(request.POST, request.FILES, instance=application)
        if form.is_valid():
            application = form.save(commit=False)

            # if application.status == 'd' and not application.photo:
            #     form.add_error('photo', 'Необходимо загрузить фотографию для заявки со статусом "Выполнена"')
            # elif application.status == 'o' and not application.comment:
            #     form.add_error('comment', 'Необходимо добавить комментарий для заявки со статусом "Принята в работу"')
            # else:
            #     application.save()
            #     return redirect('catalog:profile')

            if application.status == 'd' and not application.document:
                messages.error(request, 'Загрузите договор!')
                return render(request, 'application/edit_application.html', {'form': form, 'application': application})
            if application.document and user.tariff != 'company':
                messages.error(request, 'Только для юр.лиц!')
                return render(request, 'application/edit_application.html', {'form': form, 'application': application})

            application.save()
            return redirect('catalog:admin_profile')
    else:
        form = ApplicationAdminForm(instance=application)

    return render(request, 'application/edit_application.html', {'form': form, 'application': application})


@login_required
@user_passes_test(lambda u: u.is_staff)
def admin_profile(request):
    applications = Application.objects.all()
    return render(request, 'registration/admin_profile.html', {'applications': applications})

catalog/templates/index.html
{% load static %} {% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_css %} {% bootstrap_javascript jquery='slim' %}
    <title>{% block title %} Главная {% endblock %}</title>
</head>
<body style="background-color: 	#FFFAF0">
<style>
    .app-img {
        height: 200px;
        object-fit: cover;
    }
</style>
<div class="container-fluid">
    <div style="background-color: #FFFAF0;" class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3 border-bottom box-shadow">
        <h1 class="mr-md-auto p-2">Design.pro</h1>
        {% if user.is_authenticated %}
        <form class="p-2 text-dark" action="{% url 'catalog:profile' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Профиль</button>
        </form>
        <form class="p-2 text-dark" action="{% url 'catalog:logout'%}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Выйти</button>
        </form>
        {% else %}
        <form class="p-2 text-dark" action="{% url 'catalog:register' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Регистрация</button>
        </form>
        <form class="p-2 text-dark" action="{% url 'catalog:login' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item" type="submit">Вход</button>
        </form>
        {% endif %}
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column" style="margin: 15px;">
            <a style="color: black;" class="nav-link root" href="{% url 'catalog:index' %}">Главная</a>
                {% if user.is_staff %}
                    <a style="color: black;" class="nav-link root" href="{% url 'catalog:admin_profile' %}">Профиль администратора</a>
                {% endif %}
        </nav>
        <div class="container"> {% bootstrap_messages %}
            {% block content %}
                <p class="p-2 text-dark">Заявок принятых в работу: {{ num_application_in_work }}</p>
                <h3 class="p-2 text-dark">Последние заявки</h3>
            {% if applications %}
        <div class="row">
            {% for application in applications %}
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card">
                    {% if application.photo %}
                    <img src="{{ application.photo.url }}" class="card-img-top app-img" alt="Фото заявки">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{ application.date }}</p>
                        <h5 class="card-title">{{ application.name }}</h5>
                        <p class="card-text">{{ application.description }}</p>
                        <p class="card-text">Статус: {{ application.get_status_display }}</p>
                        <p class="card-text">Категории: {{ application.categories.all|join:', ' }}</p>
                        <p class="card-text">Цена: {{ application.price }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
    <div class="row">
        <div class="col-12">
            <p class="text-center">У вас нет заявок.</p>
        </div>
    </div>
    {% endif %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>